#!/usr/bin/env python
import os

import responses

from imgutils.entry import imgutils

_RESPONSE_TOML = os.path.join(os.path.dirname(__file__), 'responses.toml')


@responses.activate
def imgutils_with_fake_response():
    responses._add_from_file(_RESPONSE_TOML)
    imgutils()
    responses.reset()


if __name__ == '__main__':
    imgutils_with_fake_response()
